### ISSUE TITLE
Opsplitsen

### ISSUE THREAD

**Issue by Mokerstier** [joordy/PhotoPaint-PWA#12]
https://github.com/joordy/PhotoPaint-PWA/blob/d761328b25b568be804eb1feda024beba561a499/src/routes/router.js#L16

Misschien een mooie om je routes visueel op te splitsen nog:

```
//get Routes
.get(getRouteA)
.get(getRouteB)
.get(getRouteC)
.get(getRouteD)

// post Routes
.post(postRouteA)
.post(etc.. je snapt me wel denk ik
```

**Comment by joordy** [comment]
Fixed ✅
