### ISSUE TITLE
Render naar buiten verplaatse

### ISSUE THREAD

**Issue by Mokerstier** [joordy/PhotoPaint-PWA#13]
https://github.com/joordy/PhotoPaint-PWA/blob/d761328b25b568be804eb1feda024beba561a499/src/routes/renders/detail.js#L1

Ik zou de render folder, buiten de routes folder plaatsen. 
Ik schrok me nu een hoedje omdat ik hem hier niet verwachte :) (beetje overdrijven mag wel ;))

**Comment by joordy** [comment]
Fixed ✅
