### ISSUE TITLE
Peer feedback W1

### ISSUE THREAD

**Issue by lars-ruijs** [joordy/PhotoPaint-PWA#7]
# Rubrics:

## App structure and code quality

> You can structure your code by applying patterns. You can substantiate the choice for the chosen patterns

- [x] The code contains no syntax errors and is neatly formatted
- [x] You have separated your code into modules

### Tips
- [ ] You could consider using ES6 imports instead of using `require('module')`

## Retrieve, manipulate and display data

> "You can retrieve data, manipulate it and convert it dynamically to html elements using templating.
You understand how to work with an external API using asynchronous code. "

- [x] JSON data can be retrieved from an API with an asynchronous request
- [x] JSON data can be rendered server side
- [x] You have used a templating engine (handlebars)

## Handle states and routes

> You understand how to manage states in your applications and inform the user about states where necessary.

- [x] Routing & states can be managed 

---

# Repository 

- [x] Is there a repo description at the top?
- [x] Is the repo open to issues?
- [x] Does it include a .gitignore
- [x] Is the API described in the readme?
- [x] Link to live demo in the about section

### Tips
- [ ] Include a description of your concept
- [ ] Change the title of the readme from "Web App From Scratch" to "Progressive Web Apps"
- [ ] Maybe include a screenshot of your application
- [ ] Include a link to the live demo in your readme

---

## Click through the live demo
- [x] Does it work the way you would expect it to?
- [x] The app displays an overview and detail page (even when JavaScript is disabled)
- [x] The search function of the app works
- [x] The application looks very good!

### Tips
- For some reason, the search icon and user icon disappear when disabling JavaScript.
- The profile page shows missing images.
- Maybe show a error message when no images are found (after searching)

## BROWSE the code
- [x] Check the code for consistency, is code being written the same way in different places?
- [x] Does the code follow naming conventions? Do variable and function names make sense to you?

--- 

You have been super productive this week. Keep up the good work!

**Comment by joordy** [comment]
# To Fix: 

- [x] Convert require to imports
- [x]  Include a description of your concept
- [x]  Change the title of the readme from "Web App From Scratch" to "Progressive Web Apps"
- [x]  Maybe include a screenshot of your application
- [x]  Include a link to the live demo in your readme
